### ISSUE TITLE
加载依赖失败

### ISSUE THREAD

**Issue by miller8** [jenly1314/Base#5]
Could not determine the dependencies of task ':base:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':base:debugCompileClasspath'.
   > Could not resolve com.github.jenly1314.Base:uitl:3.2.1-androidx.
     Required by:
         project :base
      > Could not resolve com.github.jenly1314.Base:uitl:3.2.1-androidx.
         > Could not get resource 'https://jcenter.bintray.com/com/github/jenly1314/Base/uitl/3.2.1-androidx/uitl-3.2.1-androidx.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jenly1314/Base/uitl/3.2.1-androidx/uitl-3.2.1-androidx.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by jenly1314** [comment]
[![JitPack](https://jitpack.io/v/jenly1314/Base.svg)](https://jitpack.io/#jenly1314/Base)
